### BUILD STAGE ###
FROM node:22-slim AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build   # → dist 생성


### PRODUCTION STAGE ###
FROM node:22-slim

WORKDIR /usr/src/app

# package.json만 복사 후 prod deps만 설치
COPY package*.json ./
RUN npm install --omit=dev

# dist만 복사
COPY --from=builder /usr/src/app/dist ./dist
COPY .env ./.env

EXPOSE 9090

CMD ["node", "dist/app.js"]
