# docker-compose.yml (dev)

services:
  test-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test-server
    ports:
      - "9090:9090"
      - "9229:9229"   # ← 디버깅용 (중요)
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 100

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    command: npm run dev
