server:
  port: 9100

spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs