[versions]
kotlin = "2.3.21"
springBoot = "4.1.0"
springDependencyManagement = "1.1.7"
# swagger
springdoc = "3.1.0"
# aws
awsSdk = "2.54.8"
# jwt
jjwt = "0.12.6"
# kover
kover = "0.9.9"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot-framework = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-security-crypto = { module = "org.springframework.security:spring-security-crypto" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
aws-sdk-signin = { module = "software.amazon.awssdk:signin" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awsSdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
